// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinance.Data;

#nullable disable

namespace MyFinance.Data.Migrations
{
    [DbContext(typeof(MyFinanceDbContext))]
    [Migration("20260823142542_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MyFinance.Core.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumberMasked")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("USD");

                    b.Property<string>("Institution")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastReconciledBalance")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastReconciledOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("OpenedOn")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsClosed", "SortOrder");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.BudgetLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RollsOver")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "PeriodStart", "PeriodType")
                        .IsUnique();

                    b.ToTable("BudgetLines", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.CategorizationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastAppliedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchField")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetPayeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesApplied")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TargetCategoryId");

                    b.HasIndex("TargetPayeeId");

                    b.HasIndex("IsEnabled", "Priority", "Id");

                    b.ToTable("CategorizationRules", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTaxRelated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriesCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicatesSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ImportedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReverted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayeesCreated")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionsAdded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ImportedUtc");

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.Payee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastCategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName");

                    b.ToTable("Payees", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.PayeeAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedPattern")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PayeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPattern")
                        .IsUnique();

                    b.HasIndex("PayeeId");

                    b.ToTable("PayeeAliases", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.ScheduleOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActualAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduledTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("ScheduledTransactionId", "DueDate")
                        .IsUnique();

                    b.HasIndex("State", "DueDate");

                    b.ToTable("ScheduleOccurrences", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.ScheduledTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoEnter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysAheadToEnter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEstimate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PayeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondDayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekendShift")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PayeeId");

                    b.HasIndex("IsActive", "StartDate");

                    b.ToTable("ScheduledTransactions", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.ScheduledTransactionSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduledTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ScheduledTransactionId");

                    b.ToTable("ScheduledTransactionSplits", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClearedStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FitId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVoid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PayeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduledTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceInDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransferPeerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("PayeeId");

                    b.HasIndex("ScheduledTransactionId");

                    b.HasIndex("TransferPeerId")
                        .IsUnique();

                    b.HasIndex("AccountId", "FitId")
                        .IsUnique()
                        .HasFilter("\"FitId\" IS NOT NULL");

                    b.HasIndex("AccountId", "Date", "SequenceInDay", "Id");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.TransactionSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionSplits", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.WatchedCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.ToTable("WatchedCategories", (string)null);
                });

            modelBuilder.Entity("MyFinance.Core.Entities.BudgetLine", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.CategorizationRule", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyFinance.Core.Entities.Category", "TargetCategory")
                        .WithMany()
                        .HasForeignKey("TargetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyFinance.Core.Entities.Payee", "TargetPayee")
                        .WithMany()
                        .HasForeignKey("TargetPayeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("TargetCategory");

                    b.Navigation("TargetPayee");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.Category", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.ImportBatch", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.Payee", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Category", "LastCategory")
                        .WithMany()
                        .HasForeignKey("LastCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastCategory");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.PayeeAlias", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Payee", "Payee")
                        .WithMany("Aliases")
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payee");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.ScheduleOccurrence", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.ScheduledTransaction", "ScheduledTransaction")
                        .WithMany("Occurrences")
                        .HasForeignKey("ScheduledTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFinance.Core.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ScheduledTransaction");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.ScheduledTransaction", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFinance.Core.Entities.Payee", "Payee")
                        .WithMany()
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Payee");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.ScheduledTransactionSplit", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyFinance.Core.Entities.ScheduledTransaction", "ScheduledTransaction")
                        .WithMany("Splits")
                        .HasForeignKey("ScheduledTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ScheduledTransaction");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.Transaction", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFinance.Core.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Transactions")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinance.Core.Entities.Payee", "Payee")
                        .WithMany("Transactions")
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinance.Core.Entities.ScheduledTransaction", "ScheduledTransaction")
                        .WithMany()
                        .HasForeignKey("ScheduledTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinance.Core.Entities.Transaction", "TransferPeer")
                        .WithOne()
                        .HasForeignKey("MyFinance.Core.Entities.Transaction", "TransferPeerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("ImportBatch");

                    b.Navigation("Payee");

                    b.Navigation("ScheduledTransaction");

                    b.Navigation("TransferPeer");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.TransactionSplit", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyFinance.Core.Entities.Transaction", "Transaction")
                        .WithMany("Splits")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.WatchedCategory", b =>
                {
                    b.HasOne("MyFinance.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.ImportBatch", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.Payee", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.ScheduledTransaction", b =>
                {
                    b.Navigation("Occurrences");

                    b.Navigation("Splits");
                });

            modelBuilder.Entity("MyFinance.Core.Entities.Transaction", b =>
                {
                    b.Navigation("Splits");
                });
#pragma warning restore 612, 618
        }
    }
}
